environment=PROD

#Log Output
logging.file.name=application.log

# Log Levels
logging.level.root=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=ERROR
logging.level.com.bridgelabz=DEBUG

# Logging pattern for file logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %msg%n

# Disabling console logging and Spring banner in production
logging.pattern.console=
spring.main.banner-mode=off
